### ISSUE TITLE
Widevine key persistence

### ISSUE THREAD

**Issue by xam60** [AnassHmida/react-native-video-drm#2]
Hello,
Is there any modification to do to implement key persistence on Widevine DRM compared to react-native-video ?
I tried your repo code in place of react-native-video but unfortunately, the player is requesting a license each time it launches a live stream dash widevine.
I want to implement key persistence / caching for a live stream service : it would reduce the loading time when it already has the license key

My code : 
```
<Video
source={{ uri: 'dashurl.mpd', type: 'mpd' }}

drm={{
        type: 'widevine', 
        licenseServer: 'widevinelicenseurl',
        headers: {
            'Authorization': 'Bearer=yourtoken'
        },
}}

ref={(ref) => {
this.player = ref
}}
style={styles.video}
fullscreen={true}
controls={true}
 />
```

**Comment by AnassHmida** [comment]
@xam60  Hello ! maybe you didn't implement it right ?

Try this code below : 

Note : if you have widevine license url for your playback use it , if you don't then leave it empty and the player will fetch the licenseurl from the mpd file if provided inside it. 


```

 <Video
        ref={video}
        token={tokenValue}
        source={{
          token: tokenValue,
          uri: track,
          type: Platform.OS === 'android' ? 'mpd' : 'm3u8',
        }}
        drm={
          Platform.OS === 'android'
            ? {
              type: 'widevine',
              licenseServer: '',
              headers: {
                Authorization: token,
              },
            }
            : {
              type: 'fairplay',
              certificateUrl: 'fps.cer',
              headers: {
                Authorization: token,
              },
            }
        }
        rate={rate}
        paused={paused}
        muted={Buffering}
        minLoadRetryCount={2}
        repeat={false}
        onAudioFocusChanged={e => onAudioFocusChanged(e.hasAudioFocus)}
        onPlaybackRateChange={playback => onPlaybackRateChange(playback)}
        onProgress={data => onPlayerProgress(data)}
        onLoadStart={() => onStartLoding()}
        onLoad={info => onPlayerLoad(info)}
        onBuffer={() => onBuffer()}
        // controls
        onError={() => onError()}
        progressUpdateInterval={1000}
        onEnd={() => onCurrentEnd()}
        onReadyForDisplay={() => onReadyForDisplay()}
      />

```

let me know if you need any other help.

**Comment by xam60** [comment]
Hello @AnassHmida 

Thanks for your reply.
I tried adding some of your options (I don't have every built-in functions onload, on progress so I got a lot of errors), without success.

I though an option was needing to enable the caching of the widevine license but it seems not, thanks for your feedback.
